/*
Generated by UnityTwine on 2/13/2017 10:23:41 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class Level1Story: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
	}
    
	// .............
	// #0: StoryTitle

	void passageInit_0()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"Shade");	
	}
    
	// .............
	// #1: MC: Hello, I�m from the research department, I was wondering, is it possible to have the data on my holophone restored? It�s important.

	void passageInit_1()
	{
		this.Passages["MC: Hello, I�m from the research department, I was wondering, is it possible to have the data on my holophone restored? It�s important."] = new TwinePassage("MC: Hello, I�m from the research department, I was wondering, is it possible to have the data on my holophone restored? It�s important.", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineText(@"Kazkaza ( sigh and then sarcasm): Let me guess, you drank too many �elements� at the company dinner party, ended up with some strange person who robbed you bli-");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(assertive) No, nothing like that!I got into an accident and the information on my holophone is really important!", @"(assertive) No, nothing like that!I got into an accident and the information on my holophone is really important!", @"(assertive) No, nothing like that!I got into an accident and the information on my holophone is really important!", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"(calm) Appologies, nothing that interesting. Or so I think...I can't remember and the information on my holophone could help me.""", @"(calm) Appologies, nothing that interesting. Or so I think...I can't remember and the information on my holophone could help me.""", @"(calm) Appologies, nothing that interesting. Or so I think...I can't remember and the information on my holophone could help me.""", null, null);	
	}
    
	// .............
	// #2: (assertive) No, nothing like that!I got into an accident and the information on my holophone is really important!

	void passageInit_2()
	{
		this.Passages["(assertive) No, nothing like that!I got into an accident and the information on my holophone is really important!"] = new TwinePassage("(assertive) No, nothing like that!I got into an accident and the information on my holophone is really important!", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"Kazkaza ( annoyed) : �That�s not my issue. ( mumbles) Everyone's gotta take out their issues on IT.�  (sigh) � I�ll do it, it won�t be easy since I have to pull it from the cloud and I have other work to do y�anno, it�s not like you're the only one with holophone issues right now.�");
		yield return new TwineText(@"");
		yield return new TwineLink(@"�Well It�ll go faster if you help me out with a problem��", @"�Well It�ll go faster if you help me out with a problem��", @"�Well It�ll go faster if you help me out with a problem��", null, null);	
	}
    
	// .............
	// #3: (calm) Appologies, nothing that interesting. Or so I think...I can't remember and the information on my holophone could help me."

	void passageInit_3()
	{
		this.Passages["(calm) Appologies, nothing that interesting. Or so I think...I can't remember and the information on my holophone could help me.\""] = new TwinePassage("(calm) Appologies, nothing that interesting. Or so I think...I can't remember and the information on my holophone could help me.\"", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"Kazkaza ( mischievious) : � Well, maybe you really did end up drinking too much at the company party, hmm? Well, no matter, I have quite a bit of work to do, but I�ll work on getting your phones information restored, It�ll be kinda a pain though, and it might take a while for me to bring all the data back to you, I tell ya, cloud storage is one hell of a pain!�");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"�Well It�ll go faster if you help me out with a problem��", @"�Well It�ll go faster if you help me out with a problem��", @"�Well It�ll go faster if you help me out with a problem��", null, null);	
	}
    
	// .............
	// #4: �Well It�ll go faster if you help me out with a problem��

	void passageInit_4()
	{
		this.Passages["�Well It�ll go faster if you help me out with a problem��"] = new TwinePassage("�Well It�ll go faster if you help me out with a problem��", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"MC:I guess I could? Depending on what it is, if it helps you get my phones data back sooner.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Kazkaza: It�s nothing really, I just need you to pick up a box of parts I ordered for some repairs. I�ll mark the location on your holophone�s holopath.", @"Kazkaza: It�s nothing really, I just need you to pick up a box of parts I ordered for some repairs. I�ll mark the location on your holophone�s holopath.", @"Kazkaza: It�s nothing really, I just need you to pick up a box of parts I ordered for some repairs. I�ll mark the location on your holophone�s holopath.", null, null);	
	}
    
	// .............
	// #5: Starting area

	void passageInit_5()
	{
		this.Passages["Starting area"] = new TwinePassage("Starting area", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"MC wakes up in a hospital and finds a strange man looming above MC");
		yield return new TwineText(@"");
		yield return new TwineText(@"""Ugh...""");	
	}
    
	// .............
	// #6: Untitled Passage

	void passageInit_6()
	{
		this.Passages["Untitled Passage"] = new TwinePassage("Untitled Passage", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"Doctor Evian ( nonchalantly):  Ah, you�ve awoken, good, good. Do you understand what I�m saying right now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"MC : �...yes�. What happened to me? Where is this?�", @"MC : �...yes�. What happened to me? Where is this?�", @"MC : �...yes�. What happened to me? Where is this?�", null, null);	
	}
    
	// .............
	// #7: MC : �...yes�. What happened to me? Where is this?�

	void passageInit_7()
	{
		this.Passages["MC : �...yes�. What happened to me? Where is this?�"] = new TwinePassage("MC : �...yes�. What happened to me? Where is this?�", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"Doctor Evian:  �Not sure, you were brought here, and I took care of you!�");
		yield return new TwineText(@"");
		yield return new TwineLink(@"MC: What�..but, where is this? Why can�t I remember how I got here, or any reason why I would be here? I was at home last time I-", @"MC: What�..but, where is this? Why can�t I remember how I got here, or any reason why I would be here? I was at home last time I-", @"MC: What�..but, where is this? Why can�t I remember how I got here, or any reason why I would be here? I was at home last time I-", null, null);	
	}
    
	// .............
	// #8: MC: What�..but, where is this? Why can�t I remember how I got here, or any reason why I would be here? I was at home last time I-

	void passageInit_8()
	{
		this.Passages["MC: What�..but, where is this? Why can�t I remember how I got here, or any reason why I would be here? I was at home last time I-"] = new TwinePassage("MC: What�..but, where is this? Why can�t I remember how I got here, or any reason why I would be here? I was at home last time I-", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"Doctor Evian : �Ah! Interesting! Memory issues! I didn�t think-�");
		yield return new TwineText(@"");
		yield return new TwineLink(@" (Loud sound erupts like glass breaking, or something breaking perhaps)", @" (Loud sound erupts like glass breaking, or something breaking perhaps)", " (Loud sound erupts like glass breaking, or something breaking perhaps)", null, null);	
	}
    
	// .............
	// #9:  (Loud sound erupts like glass breaking, or something breaking perhaps)

	void passageInit_9()
	{
		this.Passages[" (Loud sound erupts like glass breaking, or something breaking perhaps)"] = new TwinePassage(" (Loud sound erupts like glass breaking, or something breaking perhaps)", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"Doctor Evian:  NO!! THEY CANNOT COME HERE!");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(Doctor Evian rushes out of the room out of sight)", @"(Doctor Evian rushes out of the room out of sight)", @"(Doctor Evian rushes out of the room out of sight)", null, null);	
	}
    
	// .............
	// #10: (Doctor Evian rushes out of the room out of sight)

	void passageInit_10()
	{
		this.Passages["(Doctor Evian rushes out of the room out of sight)"] = new TwinePassage("(Doctor Evian rushes out of the room out of sight)", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"Double-click this passage to edit it.");	
	}
    
	// .............
	// #11: Post hospital exit

	void passageInit_11()
	{
		this.Passages["Post hospital exit"] = new TwinePassage("Post hospital exit", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"MC: �Wiped?..... That� can�t be right...why would I?....If I contact IT I think they can fix this for me� I can�t stand not knowing what happened� it sounds too out of place.�");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(MC calls IT branch of Equinox)", @"(MC calls IT branch of Equinox)", @"(MC calls IT branch of Equinox)", null, null);	
	}
    
	// .............
	// #12: (MC calls IT branch of Equinox)

	void passageInit_12()
	{
		this.Passages["(MC calls IT branch of Equinox)"] = new TwinePassage("(MC calls IT branch of Equinox)", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"Kazkaza :  Hello, this is Equinox, � Advancement through Technology� is our prime principle, this is Kazkaza speaking, how may I help you?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"MC: Hello, I�m from the research department, I was wondering, is it possible to have the data on my holophone restored? It�s important.", @"MC: Hello, I�m from the research department, I was wondering, is it possible to have the data on my holophone restored? It�s important.", @"MC: Hello, I�m from the research department, I was wondering, is it possible to have the data on my holophone restored? It�s important.", null, null);	
	}
    
	// .............
	// #13: Kazkaza: It�s nothing really, I just need you to pick up a box of parts I ordered for some repairs. I�ll mark the location on your holophone�s holopath.

	void passageInit_13()
	{
		this.Passages["Kazkaza: It�s nothing really, I just need you to pick up a box of parts I ordered for some repairs. I�ll mark the location on your holophone�s holopath."] = new TwinePassage("Kazkaza: It�s nothing really, I just need you to pick up a box of parts I ordered for some repairs. I�ll mark the location on your holophone�s holopath.", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #14: Untitled Passage 1

	void passageInit_14()
	{
		this.Passages["Untitled Passage 1"] = new TwinePassage("Untitled Passage 1", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #15: Big Boss Arch

	void passageInit_15()
	{
		this.Passages["Big Boss Arch"] = new TwinePassage("Big Boss Arch", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"MC:  Hello, you wouldn�t happen to know where I can find someone who is incharge of this place, or someone who would know where I can find some boxes for pickup, would you?");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Big Boss : Ya betcha I would. Ya looking at the Big Boss �imself! What�cha looking for squirt?� ", @"Big Boss : Ya betcha I would. Ya looking at the Big Boss �imself! What�cha looking for squirt?� ", @"Big Boss : Ya betcha I would. Ya looking at the Big Boss �imself! What�cha looking for squirt?� ", null, null);	
	}
    
	// .............
	// #16: Big Boss : Ya betcha I would. Ya looking at the Big Boss �imself! What�cha looking for squirt?� 

	void passageInit_16()
	{
		this.Passages["Big Boss : Ya betcha I would. Ya looking at the Big Boss �imself! What�cha looking for squirt?� "] = new TwinePassage("Big Boss : Ya betcha I would. Ya looking at the Big Boss �imself! What�cha looking for squirt?� ", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"MC: Someone named Kazkaza sent-");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Big Boss ( groans):  Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza�s been picking me noggin for them parts for a 4 days now now. The woman�s pretty persistent, at least she sent someone in person this time! ", @"Big Boss ( groans):  Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza�s been picking me noggin for them parts for a 4 days now now. The woman�s pretty persistent, at least she sent someone in person this time! ", "Big Boss ( groans):  Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza�s been picking me noggin for them parts for a 4 days now now. The woman�s pretty persistent, at least she sent someone in person this time! ", null, null);	
	}
    
	// .............
	// #17: Big Boss ( groans):  Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza�s been picking me noggin for them parts for a 4 days now now. The woman�s pretty persistent, at least she sent someone in person this time! 

	void passageInit_17()
	{
		this.Passages["Big Boss ( groans):  Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza�s been picking me noggin for them parts for a 4 days now now. The woman�s pretty persistent, at least she sent someone in person this time! "] = new TwinePassage("Big Boss ( groans):  Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza�s been picking me noggin for them parts for a 4 days now now. The woman�s pretty persistent, at least she sent someone in person this time! ", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		yield return new TwineText(@"MC ( suspicious):  Is there a problem with the parts she ordered?");
		yield return new TwineText(@"");
		yield return new TwineText(@" Big Boss ( sighs) :  Not really an issue with the parts ya see. The issue is the warehouse has been a complete wreck since those whacko cat things showed up 5 days ago. None of us can do a darn tootin� thing because of those pests!");
		yield return new TwineText(@" ");
		 yield return new TwineLink(@"MC (kindly) : � Is there some way I can get in there and get the parts myself? I need them quite urgently�", @"MC (kindly) : � Is there some way I can get in there and get the parts myself? I need them quite urgently�", "MC (kindly) : � Is there some way I can get in there and get the parts myself? I need them quite urgently�", null, null);
		yield return new TwineText(@" ");
		 yield return new TwineLink(@"MC ( annoyed): � Cats? I think I can deal with those, let me in. I�ll go grab the parts myself.�", @"MC ( annoyed): � Cats? I think I can deal with those, let me in. I�ll go grab the parts myself.�", "MC ( annoyed): � Cats? I think I can deal with those, let me in. I�ll go grab the parts myself.�", null, null);	
	}
    
	// .............
	// #18: MC (kindly) : � Is there some way I can get in there and get the parts myself? I need them quite urgently�

	void passageInit_18()
	{
		this.Passages["MC (kindly) : � Is there some way I can get in there and get the parts myself? I need them quite urgently�"] = new TwinePassage("MC (kindly) : � Is there some way I can get in there and get the parts myself? I need them quite urgently�", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		yield return new TwineText(@"Big Boss ( concerned) :  Y�anno. I don�t feel too great about letting ya in there to run around those Urgot-sent demons. But if Kazkaza aint got no time for waitin� then I suppose I can let ya in. Just don�t get hurt in there");	
	}
    
	// .............
	// #19: MC ( annoyed): � Cats? I think I can deal with those, let me in. I�ll go grab the parts myself.�

	void passageInit_19()
	{
		this.Passages["MC ( annoyed): � Cats? I think I can deal with those, let me in. I�ll go grab the parts myself.�"] = new TwinePassage("MC ( annoyed): � Cats? I think I can deal with those, let me in. I�ll go grab the parts myself.�", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		yield return new TwineText(@"Big Boss (Patronizingly) : Well, I reckon you can squirt. Go tango with the beasts then, don�t come crying to me when they get to ya!");	
	}

}