/*
Generated by UnityTwine on 2/21/2017 7:58:29 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class Story: TwineStory
{
	public TwineVar disposition;
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				case "disposition": return disposition;
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				case "disposition": disposition = value; break;
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
	}
    
	// .............
	// #0: StoryTitle

	void passageInit_0()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"Shade final proto");	
	}
    
	// .............
	// #1: Start

	void passageInit_1()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		disposition = 50;
		yield return new TwineText(@"");
		yield return new TwineText(@"The dialogue will be paraphrased and edited in certain sections to suit the need of this prototype. The MC (Siam) wakes up after a cutscene is shown, depicting flashs of memory). Siam opens their eyes and enters into a conversation with a doctor, named Doctor Evian. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: Ah, you've awoken, good, good. How do you feel? Can you hear me?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Ugh. What happened to me? Where is this?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: Not sure, you were brought here, and I took care of you!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: What?! But, where is this? Why can't I remember how I got here, or any reason why I would be here? I was at home last time I-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: Ah! Interesting! Memory issues! I didn't think-");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Loud sound erupts like glass breaking, or something breaking perhaps)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: NO!! THEY CANNOT COME HERE!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(pick an option, these choices influence your characters interactions in the game)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam: How rude! What is this place anyways?", @"Siam: How rude! What is this place anyways?", @"Negative1", null, null); 
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam: I gotta get out of this place fast, something is very wrong here!", @"Siam: I gotta get out of this place fast, something is very wrong here!", @"Positive1", null, null);	
	}
    
	// .............
	// #2: Holophone recovery

	void passageInit_2()
	{
		this.Passages["Holophone recovery"] = new TwinePassage("Holophone recovery", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"Siam: My holophone at least I still have that with me, maybe it can tell me whats going on But first I need to escape this place!");	
	}
    
	// .............
	// #3: After exiting

	void passageInit_3()
	{
		this.Passages["After exiting"] = new TwinePassage("After exiting", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"(When they exit the room they end up inside Equinox HQ and the door to the room MC was in vanishes.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: I should be able to figure out what happened, or at least get an idea if I take a look at my holophones memory??? That cannot be right! There's only one location on my holophone!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam spends time going through their holophone and searches in the phones settings, it notes that the phone's data was wiped 3 days ago.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Ugh, something is not right here. I'll contact support and see If I can find some way to restore the data.");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Siam calls support and enters contact with Kazkaza, an IT worker for Equinox, the producers of the Holophone and also the workplace of Siam)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Kazkaza's request", @"Kazkaza's request", @"Kazkaza's request", null, null);	
	}
    
	// .............
	// #4: Kazkaza's request

	void passageInit_4()
	{
		this.Passages["Kazkaza's request"] = new TwinePassage("Kazkaza's request", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"Kazkaza: Hello, this is Equinox, "" Advancement through Technology"" is our prime principle, this is Kazkaza speaking, how may I help you?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Hello, I'm from the research department, I was wondering, is it possible to have the data on my holophone restored? It's important.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Let me guess, you drank too many elements at the company dinner party, ended up with some strange person who robbed you bli-");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam(assertive/demanding): No! I got into an accident, and the information on my phone is really important! I need you to fix it immediately", @"Siam(assertive/demanding): No! I got into an accident, and the information on my phone is really important! I need you to fix it immediately", @"Negative Siam Kazkaza", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam (calm):  Apologies, nothing that interesting. Or so I think, I can't remember, and the information on my phone would be important on figuring out what's wrong.", @"Siam (calm):  Apologies, nothing that interesting. Or so I think, I can't remember, and the information on my phone would be important on figuring out what's wrong.", @"Positive Siam Kazkaza", null, null);	
	}
    
	// .............
	// #5: Level 2 warehouse

	void passageInit_5()
	{
		this.Passages["Level 2 warehouse"] = new TwinePassage("Level 2 warehouse", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineText(@"(Quick travels to electronics warehouse, couple of nondescript NPC's hanging around. And a obviously different NPC who is the boss of the warehouse.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Talk to big boss", @"Talk to big boss", @"Talk to big boss", null, null);	
	}
    
	// .............
	// #6: Talk to big boss

	void passageInit_6()
	{
		this.Passages["Talk to big boss"] = new TwinePassage("Talk to big boss", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"Siam: Hello, you wouldn't happen to know where I can find someone who is incharge of this place, or someone who would know where I can find some boxes for pickup, would you?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: Ya betcha I would. Ya looking at the Big Boss �imself! What'cha looking for squirt?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Someone named Kazkaza sent-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: Kazkaza, by Urgot �imself I knew this would happen eventually. Kazkaza's been picking me noggin for them parts for a 4 days now now. The woman's pretty persistent, at least she sent someone in person this time!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Is there a problem with the parts she ordered?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss (sighs): Not really an issue with the parts ya see. The issue is the warehouse has been a complete wreck since those whacko cat things showed up 5 days ago. None of us can do a darn tootin' thing because of those pests!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam (kindly):  Is there some way I can get in there and get the parts myself? I need them quite urgently.", @"Siam (kindly):  Is there some way I can get in there and get the parts myself? I need them quite urgently.", @"Nice Boss", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam (annoyed):  Cats? I think I can deal with those, let me in. I'll go grab the parts myself.", @"Siam (annoyed):  Cats? I think I can deal with those, let me in. I'll go grab the parts myself.", @"Smirking Boss", null, null);	
	}
    
	// .............
	// #7: If spoken to after the fact

	void passageInit_7()
	{
		this.Passages["If spoken to after the fact"] = new TwinePassage("If spoken to after the fact", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"Big Boss: Well, Urgot me twisted, ya did it squirt! Well, ya best be running back to Kazkaza, that way she can finally stop pagin' me for her parts!");	
	}
    
	// .............
	// #8: Call to Siam after level 2

	void passageInit_8()
	{
		this.Passages["Call to Siam after level 2"] = new TwinePassage("Call to Siam after level 2", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"(Siam gets a call from Kazkaza)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Hey, MC, how's it going? Find those parts yet?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Yeah, I got them, something weird is going on in that warehouse, I encountered some cats they definitely weren't normal cats either..");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Oh well, who cares, just bring them back over to Equinox HQ, I really need those parts, I've already been put far behind because they were late!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Siam can go to Equinox HQ)");	
	}
    
	// .............
	// #9: Enter Equinox

	void passageInit_9()
	{
		this.Passages["Enter Equinox"] = new TwinePassage("Enter Equinox", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"Siam enters the building, there is a main lobby and 3 wings. One for IT, One that is closed off, and One that is the hospital ward Siam came from earlier.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam goes north, enteres a room with a lot of rooms. Only 1 you can really go into, where Kazkaza is. Kazkaza's room is full of gadgets and wires and strange devices all over the place with a lot of screens.");	
	}
    
	// .............
	// #10: Meeting makeupwipes

	void passageInit_10()
	{
		this.Passages["Meeting makeupwipes"] = new TwinePassage("Meeting makeupwipes", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		yield return new TwineText(@"Kazkaza: Oh ho! You are finally here! Nice to finally meet you  after all this time!");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam (to self): Why do I have this feeling. Kazkaza feels familiar..");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam (casual): Nice to meet you as well.", @"Siam (casual): Nice to meet you as well.", @"Casual Siam", null, null); 
		yield return new TwineText(@"");
		yield return new TwineLink(@"Siam (annoyed): Same.", @"Siam (annoyed): Same.", @"Annoyed Siam", null, null);	
	}
    
	// .............
	// #11: Giving info

	void passageInit_11()
	{
		this.Passages["Giving info"] = new TwinePassage("Giving info", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		yield return new TwineText(@"(MC opens holophone and sees that there's a new document, the documents contains a photo of the strange rubbery cats the MC encountered in the warehouse and a bunch of medical notes and other things. Also gets access to another location, where the rubber cats live. Call it ""The Pits"")");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Hey these are the things I saw in th-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Doesn't concern me, now could you please leave MC? I got a lot of work to get back to now that I have those parts again! I'll let you know if I find any new information later when I have the time!");	
	}
    
	// .............
	// #12: Enter the pits

	void passageInit_12()
	{
		this.Passages["Enter the pits"] = new TwinePassage("Enter the pits", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		yield return new TwineText(@"(Won't be in prototype, but it is here)");
		yield return new TwineText(@"");
		yield return new TwineText(@"""The Pits""  is an area that's very green tinted, a lot of ooze super decrepit, looks very post apocalyptic. There's a cave somewhere, this is where the cats are.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam experiences a headache (headache servers as a reminder to players to active their vision abilities) (flashback shots) and triggers Siam's vision ability and sees a ton of footprints everywhere, with only one set of footprints standing out, heading towards the cave.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam (to self): What is this place....it's such a mess, but there seems to be a lot of  animal tracks around....can I find that creature here? ");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Siam enters a cave, the cave has multiple paths and ways to get around it.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"At the end of the puzzle (mostly using the arms) MC find what appears to be the main cat nest. There is a syringe and some broken electronic parts.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: ""What..."" (experiences headache, footprints appear all over,  flashbacks to syringe being inserted into a regular-ish wild cat)");	
	}
    
	// .............
	// #13: If we need to make it a complete story in the prototype

	void passageInit_13()
	{
		this.Passages["If we need to make it a complete story in the prototype"] = new TwinePassage("If we need to make it a complete story in the prototype", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"Change the ending temporarily in the Kazkaza giving info senario senario, you should be able to tag this on, if we need to complete it.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam's head hurts yet again while Kazkaza looks on mildly interested. At this point another series of flashbacks occurs and Siam recalls what happened.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"MC discovers that the truth around the accident. Kazkaza was working with the MC on a new project the couple days before the accident on manufacturing mutations in the residents of the city. This was so that the Equinox can have control of the people through the use of mutants . Kazkaza turns out to be the CTO of Equinox who manufactured the whole thing together with MC being the researcher behind it all. MC ended up in the accident because Kazkaza found out that MC had the best genetic match for the mutation, as the previous test subjects didn't work out due to tbeing incompatible. MC turned into a monster and ended up hurting a lot of people which is why the one wing of Equinox was abandoned, and sealed off, to hide the truth of what happened.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza muses in annoyance that the experiment didn't work out perfectly and quickly stabs Siam with another needle with a more wicked look on her face.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Let us try again. Shall we? Maybe next time you'll be more obedient!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Ending if player accumulates a greater negative disposition");	
	}
    
	// .............
	// #14: Positive ending

	void passageInit_14()
	{
		this.Passages["Positive ending"] = new TwinePassage("Positive ending", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		yield return new TwineText(@"Siam discovers that the truth around the accident. Kazkaza is the CTO of Eqinox, and doesn't actually work in IT, she is the Siam's former boss on a project she recruited them for recently. Kazkaza was working with Siam in the last week to develop a way to harness mutations, a subject Siam had been fascinated before they worked in Equinox, before they met Kazkaza. This was so that Equinox can gain control of the people through the use of mutants.Siam ended up in the accident because Kazkaza found out that Siam had the best genetic match for the mutation, as the previous test subjects didn't work out due to tbeing incompatible. Siam turned into a monster and ended up hurting a lot of people which is why the one wing of the holophone company was abandoned, and sealed off, to hide the truth of what happened.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza stares at Siam curiously as Siams face lights with renewed awareness and clarity.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: So, how do you feel?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Awful, truly awful, you made me do all those things! You made me!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: I didn't do anything, you did, remmeber? You tore those people apart you made the very mutation you currently have!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: So those shadows...they were.... that's why...");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Oh, if only you listened, Siam. But it's all fine now, we know that what you created is stable so I think we can move onto the next stage of development.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: I don't want to.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Excuse me?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: What your doing is creating weapons! I didn't come into researching this to create weapons! I did it to help people who were suffering and to improve thier lives using mutations!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: And weapons create peace! See without your ability, do you think you could have getten around the hospital? Do you think you would have been able to get those parts from the warehouse?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: YES! There are many methods to do any one thing in this world! It's not worth the cost of humanity!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(blah blah, option to kill Kazkaza  or let her live, cuts to immediate ending scene)");	
	}
    
	// .............
	// #15: Post pits

	void passageInit_15()
	{
		this.Passages["Post pits"] = new TwinePassage("Post pits", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		yield return new TwineText(@"Kazkaza calls Siam: Hey! Whatcha up to? Find anything interesting? Yes? No? Well no matter, I heard something really fun, sounds like it might be related to what's happened to you!");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: Hm what are you talking about?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: That east wing that's been closed of from regular Equinox staff! I was chatting with Big Boss a while ago and he told me about those cat things, there's a rumor in the Equinox HQ about some weird cats that some night shift staff saw. Maybe you should come back and look around? Oh hey! While you are on your way could you pick me up a couple of elements bottles? Actually never mind, boss wouldn't like me trying to solve problems while half drunk. Well bye-bye!~");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"MC:  What a strange woman well it's not like much else is going on");	
	}
    
	// .............
	// #16: Negative1

	void passageInit_16()
	{
		this.Passages["Negative1"] = new TwinePassage("Negative1", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: I don't have any of my belonging, just what is going on in here? I should check around quickly for my holophone!");	
	}
    
	// .............
	// #17: Positive1

	void passageInit_17()
	{
		this.Passages["Positive1"] = new TwinePassage("Positive1", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: I don't have anything with me, is my holophone somewhere near here? I should check quickly before I leave!");	
	}
    
	// .............
	// #18: Negative Siam Kazkaza

	void passageInit_18()
	{
		this.Passages["Negative Siam Kazkaza"] = new TwinePassage("Negative Siam Kazkaza", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: That's not my issue. Everyone's gotta take out their issues on IT.  I'll do it, it won't be easy since I have to pull it from the cloud and I have other work to do y'anno, it's not like you're the only one with holophone issues right now. ");yield return new TwineLink(@"Well it'll go faster if you help me out with a problem", @"Well it'll go faster if you help me out with a problem", @"Kazkaza Request", null, null);	
	}
    
	// .............
	// #19: Positive Siam Kazkaza

	void passageInit_19()
	{
		this.Passages["Positive Siam Kazkaza"] = new TwinePassage("Positive Siam Kazkaza", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza (mischievious): Well, maybe you really did end up drinking too much at the company party, hmm? Well, no matter, I have quite a bit of work to do, but I'll work on getting your phones information restored, It'll be kinda a pain though, and it might take a while for me to bring all the data back to you, I tell ya, cloud storage is one hell of a pain! ");yield return new TwineLink(@"Well it'll go faster if you help me out with a problem", @"Well it'll go faster if you help me out with a problem", @"Kazkaza Request", null, null);	
	}
    
	// .............
	// #20: Kazkaza Request

	void passageInit_20()
	{
		this.Passages["Kazkaza Request"] = new TwinePassage("Kazkaza Request", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		yield return new TwineText(@"Siam: I guess I could? Depending on what it is, if it helps you get my phones data back sooner");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: It's nothing really, I just need you to pick up a box of parts I ordered for some repairs. I'll mark the location on your holophone's holopath.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"(electronics warehouse location now unlocked)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Siam: I got the location, I'll head there and get your parts");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Hey! Thanks, I feel motivated to getting your holo data back already!");	
	}
    
	// .............
	// #21: Nice Boss

	void passageInit_21()
	{
		this.Passages["Nice Boss"] = new TwinePassage("Nice Boss", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: Y'anno. I don't feel too great about letting ya in there to run around those Urgot-sent demons. But if Kazkaza aint got no time for waitin' then I suppose I can let ya in. Just don't get hurt in there");	
	}
    
	// .............
	// #22: Smirking Boss

	void passageInit_22()
	{
		this.Passages["Smirking Boss"] = new TwinePassage("Smirking Boss", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss (Patronizingly): Well, I reckon you can squirt. Go tango with the beasts then, don't come crying to me when they get to ya!");	
	}
    
	// .............
	// #23: Casual Siam

	void passageInit_23()
	{
		this.Passages["Casual Siam"] = new TwinePassage("Casual Siam", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Geeze, don't be so polite, we work for the same company after all....but so does almost everyone who lives here so.....well no matter, thanks for the parts! Give me your holophone real quick. I have something that might interest you that I happened to find!");
		yield return new TwineText(@"");
		yield return new TwineText(@"- Kazkaza takes the phone and plugs it into one of the many cables lying around, after punching a few things into her keyboard she unplugs it and hands it back to MC-");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Giving info", @"Giving info", @"Giving info", null, null);	
	}
    
	// .............
	// #24: Annoyed Siam

	void passageInit_24()
	{
		this.Passages["Annoyed Siam"] = new TwinePassage("Annoyed Siam", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: You researchers, all the same, no manners. Well whatever, I found something that probably interests you, give me your holophone");
		yield return new TwineText(@"");
		yield return new TwineText(@"(note that Siam is a researcher in Equinox, will be better exposed in the actual dialogue, as with everything else)");
		yield return new TwineText(@"");
		yield return new TwineText(@"-Kazkaza takes the phone and plugs it into one of the many cables lying around, after punching a few things into her keyboard she unplugs it and hands it back to MC-");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Giving info", @"Giving info", @"Giving info", null, null);	
	}

}