/*
Generated by UnityTwine on 4/12/2017 2:13:31 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class YinFinal: TwineStory
{
	public TwineVar disposition;
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				case "disposition": return disposition;
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				case "disposition": disposition = value; break;
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
		passageInit_7();
		passageInit_8();
		passageInit_9();
		passageInit_10();
		passageInit_11();
		passageInit_12();
		passageInit_13();
		passageInit_14();
		passageInit_15();
		passageInit_16();
		passageInit_17();
		passageInit_18();
		passageInit_19();
		passageInit_20();
		passageInit_21();
		passageInit_22();
		passageInit_23();
		passageInit_24();
		passageInit_25();
		passageInit_26();
		passageInit_27();
		passageInit_28();
		passageInit_29();
		passageInit_30();
		passageInit_31();
		passageInit_32();
		passageInit_33();
		passageInit_34();
		passageInit_35();
		passageInit_36();
		passageInit_37();
		passageInit_38();
		passageInit_39();
		passageInit_40();
		passageInit_41();
		passageInit_42();
		passageInit_43();
		passageInit_44();
		passageInit_45();
		passageInit_46();
		passageInit_47();
		passageInit_48();
		passageInit_49();
		passageInit_50();
		passageInit_51();
		passageInit_52();
		passageInit_53();
		passageInit_54();
		passageInit_55();
		passageInit_56();
		passageInit_57();
		passageInit_58();
		passageInit_59();
		passageInit_60();
		passageInit_61();
		passageInit_62();
		passageInit_63();
		passageInit_64();
		passageInit_65();
		passageInit_66();
		passageInit_67();
		passageInit_68();
		passageInit_69();
		passageInit_70();
		passageInit_71();
		passageInit_72();
		passageInit_73();
		passageInit_74();
		passageInit_75();
		passageInit_76();
		passageInit_77();
		passageInit_78();
		passageInit_79();
		passageInit_80();
		passageInit_81();
		passageInit_82();
		passageInit_83();
		passageInit_84();
	}
    
	// .............
	// #0: StoryTitle

	void passageInit_0()
	{
		this.Passages["StoryTitle"] = new TwinePassage("StoryTitle", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"Yin Final");	
	}
    
	// .............
	// #1: Start

	void passageInit_1()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		disposition = 0;
		yield return new TwineText(@"");
		yield return new TwineText(@"(Shion slowly blinks awake, eyebrows furrowing in pain emenating from behind their eyes)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: Ah, you've awoken, good, good. How do you feel? Can you hear me?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Ugh. What happened to me? Where is this? Why do my eyes hurt?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: Not sure, you were brought here, and I took care of you!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: What?! But, where is this? Why can't I remember how I got here, or any reason why I would be here? I was at home last time I-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: Ah! Interesting! Memory issues! I didn't think-");
		yield return new TwineText(@"");
		yield return new TwineText(@"(A loud shattering noise sounds from behind Doctor Evian)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Doctor Evian: NO!! THEY CANNOT COME HERE!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: How rude! What is this place anyways?", @"Shion: How rude! What is this place anyways?", @"Negative1", null, null); 
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: I gotta get out of this place fast, something is very wrong here!", @"Shion: I gotta get out of this place fast, something is very wrong here!", @"Positive1", null, null);	
	}
    
	// .............
	// #2: Holophonerecoveryfirst

	void passageInit_2()
	{
		this.Passages["Holophonerecoveryfirst"] = new TwinePassage("Holophonerecoveryfirst", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		disposition = 0;
		yield return new TwineText(@"Shion: My holophone!...but it's missing the battery, where is it?");	
	}
    
	// .............
	// #3: Afterexiting

	void passageInit_3()
	{
		this.Passages["Afterexiting"] = new TwinePassage("Afterexiting", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"( As Shion exits the room a metal gate comes down, blocking the entrance of the door from being acessed again. At the same time Shions arm begins to throbb a bit.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion:...Ouch...my arm..why is it hurting?");
		yield return new TwineText(@"");
		yield return new TwineText(@"( Shion looks at their arm and notices nothing out of the ordinary aside from the slight green twinge to the skin.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Strange...anyways...I should be able to figure out what happened, or at least get an idea if I take a look at my holophones memory??? That cannot be right! There's only one location on my holophone!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion spends time going through their holophone and searches in the phones settings, it notes that the phone's data was wiped 3 days ago.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Ugh, something is not right here. I'll contact support and see If I can find some way to restore the data.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(Contacts Equinox's Holosupport number)", @"(Contacts Equinox's Holosupport number)", @"Kazkazasrequest", null, null);	
	}
    
	// .............
	// #4: Kazkazasrequest

	void passageInit_4()
	{
		this.Passages["Kazkazasrequest"] = new TwinePassage("Kazkazasrequest", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineText(@"Kazkaza: Hello, this is Equinox, ""Advancement through Technology"" is our prime principle, this is Kazkaza speaking, how may I help you?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Hello, I'm from the research department, I was wondering, is it possible to have the data on my holophone restored? It's important.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Let me guess, you drank too many elements at the company dinner party, ended up with some strange person who robbed you bli-");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: No! I got into an accident, and the information on my phone is really important! I need you to fix it immediately!", @"Shion: No! I got into an accident, and the information on my phone is really important! I need you to fix it immediately!", @"NegativeShionKazkaza", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion:  Apologies, nothing that interesting. Or so I think, I can't remember, and the information on my phone would be important on figuring out what's wrong.", @"Shion:  Apologies, nothing that interesting. Or so I think, I can't remember, and the information on my phone would be important on figuring out what's wrong.", @"PositiveShionKazkaza", null, null);	
	}
    
	// .............
	// #5: Level2warehouse

	void passageInit_5()
	{
		this.Passages["Level2warehouse"] = new TwinePassage("Level2warehouse", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		disposition = 0;
		yield return new TwineText(@"");
		yield return new TwineText(@"(Shion moves to a warehouse, couple of nondescript NPC's hanging around. And a obviously different NPC who is the boss of the warehouse.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(Talk to Big Boss)", @"(Talk to Big Boss)", @"Talktobigboss", null, null);	
	}
    
	// .............
	// #6: Talktobigboss

	void passageInit_6()
	{
		this.Passages["Talktobigboss"] = new TwinePassage("Talktobigboss", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineText(@"Shion: Hello, you wouldn't happen to know where I can find someone who is incharge of this place, or someone who would know where I can find some boxes for pickup, would you?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: Ya betcha I would. Ya looking at the Big Boss ‘imself! What'cha looking for squirt?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Someone named Kazkaza sent-");
		yield return new TwineText(@"");
		yield return new TwineLink(@"continue", @"continue", @"Talktobigboss2", null, null);	
	}
    
	// .............
	// #7: Ifspokentoafterobtainingparts

	void passageInit_7()
	{
		this.Passages["Ifspokentoafterobtainingparts"] = new TwinePassage("Ifspokentoafterobtainingparts", new string[]{  }, passageExecute_7);
	}

	IEnumerable<TwineOutput> passageExecute_7()
	{
		yield return new TwineText(@"Big Boss: Well, Urgot me twisted, ya did it squirt! Well, ya best be running back to Kazkaza, that way she can finally stop pagin' me for her parts!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level2End", null, null);	
	}
    
	// .............
	// #8: CalltoShionafterlevel2

	void passageInit_8()
	{
		this.Passages["CalltoShionafterlevel2"] = new TwinePassage("CalltoShionafterlevel2", new string[]{  }, passageExecute_8);
	}

	IEnumerable<TwineOutput> passageExecute_8()
	{
		yield return new TwineText(@"(Shion gets a call from Kazkaza)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Hey, Shion, how's it going? Find those parts yet?");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Yeah, I got them, something weird is going on in that warehouse, I encountered moving shadows, monsters!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Oh well, who cares, just bring them back over to Equinox HQ, I really need those parts, I've already been put far behind because they were late! Bye now!~");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: I should go to Kazkaza's office and drop these off...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level2End", null, null);	
	}
    
	// .............
	// #9: EnterEquinox

	void passageInit_9()
	{
		this.Passages["EnterEquinox"] = new TwinePassage("EnterEquinox", new string[]{  }, passageExecute_9);
	}

	IEnumerable<TwineOutput> passageExecute_9()
	{
		yield return new TwineText(@"Shion: I'm finally back, I should go deliver these to Kazkaza quickly.");	
	}
    
	// .............
	// #10: Meetingmakeupwipes

	void passageInit_10()
	{
		this.Passages["Meetingmakeupwipes"] = new TwinePassage("Meetingmakeupwipes", new string[]{  }, passageExecute_10);
	}

	IEnumerable<TwineOutput> passageExecute_10()
	{
		disposition = 0;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Oh ho! You are finally here! Nice to finally meet you after all this time!");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Why do I have this feeling as if this is not our first encounter. Kazkaza feels familiar...");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: Nice to meet you as well!", @"Shion: Nice to meet you as well!", @"CasualShion", null, null); 
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: Same...", @"Shion: Same...", @"AnnoyedShion", null, null);	
	}
    
	// .............
	// #11: Negative1

	void passageInit_11()
	{
		this.Passages["Negative1"] = new TwinePassage("Negative1", new string[]{  }, passageExecute_11);
	}

	IEnumerable<TwineOutput> passageExecute_11()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion:I don't have any of my belongings, just what is going on in here? I should check around quickly for my holophone!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level1End", null, null);	
	}
    
	// .............
	// #12: Positive1

	void passageInit_12()
	{
		this.Passages["Positive1"] = new TwinePassage("Positive1", new string[]{  }, passageExecute_12);
	}

	IEnumerable<TwineOutput> passageExecute_12()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: I don't have anything with me... my holophone, did they take it away from me? Did I lose it? It wouldn't hurt to look around quickly as I escape from here...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level1End", null, null);	
	}
    
	// .............
	// #13: KazkazaRequest

	void passageInit_13()
	{
		this.Passages["KazkazaRequest"] = new TwinePassage("KazkazaRequest", new string[]{  }, passageExecute_13);
	}

	IEnumerable<TwineOutput> passageExecute_13()
	{
		yield return new TwineText(@"Shion: I guess I could? Depending on what it is, if it helps you get my phones data back sooner");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: It's nothing really, I just need you to pick up a box of parts I ordered for some repairs. I'll mark the location on your holophone's holopath.");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"(electronics warehouse location now unlocked)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: I got the location, I'll head there and get your parts");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Hey! Thanks, I feel motivated to getting your holo data back already! ");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"KazkazarequestEnd", null, null);	
	}
    
	// .............
	// #14: NiceBoss

	void passageInit_14()
	{
		this.Passages["NiceBoss"] = new TwinePassage("NiceBoss", new string[]{  }, passageExecute_14);
	}

	IEnumerable<TwineOutput> passageExecute_14()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: Y'anno. I don't feel too great about letting ya in there to run around those Urgot-sent demons. But if Kazkaza aint got no time for waitin' then I suppose I can let ya in. Just don't get hurt in there!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Access to the inside of the warehouse is unlocked)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: One thing there kiddo! There's a seal that we were using to keep those shadow monsters outta the stock, problem is someone didn't activate the seal properly so those monsters ran all over the warehouse. Once you get in there I can't let you out until you activate the seal properly! Take a look at this picture real quick, and memorize it. It'll give you an idea of what to do with the seal, and here's another picture of the parts for Kazkaza. Good luck!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level2End", null, null);	
	}
    
	// .............
	// #15: SmirkingBoss

	void passageInit_15()
	{
		this.Passages["SmirkingBoss"] = new TwinePassage("SmirkingBoss", new string[]{  }, passageExecute_15);
	}

	IEnumerable<TwineOutput> passageExecute_15()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss : Well, I reckon you can squirt. Go tango with the beasts then, don't come crying to me when they get to ya!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Access to the inside of the warehouse is unlocked)");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: One thing there kiddo! There's a seal that we were using to keep those shadow monsters outta the stock, problem is someone didn't activate the seal properly so those monsters ran all over the warehouse. Once you get in there I can't let you out until you activate the seal properly! Take a look at this picture real quick, and memorize it. It'll give you an idea of what to do with the seal, and here's another picture of the parts for Kazkaza. Good luck!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level2End", null, null);	
	}
    
	// .............
	// #16: Givinginfo

	void passageInit_16()
	{
		this.Passages["Givinginfo"] = new TwinePassage("Givinginfo", new string[]{  }, passageExecute_16);
	}

	IEnumerable<TwineOutput> passageExecute_16()
	{
		yield return new TwineText(@"Shion: Hey,these are the things I saw in the-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Doesn't concern me, now could you please leave, Shion? I have a great deal of work to get back to, now that I have those parts again.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion:I'll leave you to it Kazkaza, let me know if you find any more information.", @"Shion:I'll leave you to it Kazkaza, let me know if you find any more information.", @"KindShion", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: Fine! I'll get out of your hair! Just let me know if you find anymore information.", @"Shion: Fine! I'll get out of your hair! Just let me know if you find anymore information.", @"AnnoyShion", null, null);	
	}
    
	// .............
	// #17: KindShion

	void passageInit_17()
	{
		this.Passages["KindShion"] = new TwinePassage("KindShion", new string[]{  }, passageExecute_17);
	}

	IEnumerable<TwineOutput> passageExecute_17()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Well, doesn't look like there's anything else to do here, I should find more information on this closed wing, I have a feeling I can get my memories back there.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"MeetingmakeupwipesEnd", null, null);	
	}
    
	// .............
	// #18: AnnoyShion

	void passageInit_18()
	{
		this.Passages["AnnoyShion"] = new TwinePassage("AnnoyShion", new string[]{  }, passageExecute_18);
	}

	IEnumerable<TwineOutput> passageExecute_18()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Well, I should get going, not like there's anything else to do here. I should see If I can find anymore information on this closed wing. I think something important happened there, something I did.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"MeetingmakeupwipesEnd", null, null);	
	}
    
	// .............
	// #19: EquinoxNPCstalking

	void passageInit_19()
	{
		this.Passages["EquinoxNPCstalking"] = new TwinePassage("EquinoxNPCstalking", new string[]{  }, passageExecute_19);
	}

	IEnumerable<TwineOutput> passageExecute_19()
	{
		disposition = 0;
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"( Shion walks up to two Equinox employee's chatting in the hallway who wave at Shion on approach)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee ( male): Oh! Hey Shion, long time no see!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee ( female): It's been what? A couple weeks no hasn't it?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion:Yeah...I guess? How have you been?", @"Shion:Yeah...I guess? How have you been?", @"NPC1ShionConfused", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion:Who the heck are you two?", @"Shion:Who the heck are you two?", @"NPC1ShionRage", null, null);	
	}
    
	// .............
	// #20: NPC1ShionConfused

	void passageInit_20()
	{
		this.Passages["NPC1ShionConfused"] = new TwinePassage("NPC1ShionConfused", new string[]{  }, passageExecute_20);
	}

	IEnumerable<TwineOutput> passageExecute_20()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee (female): It's going all right... anyways you came at the perfect time. Don't you work in the research division? Maybe you know about what's going on lately.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee (male): You talking about those shadow beasts?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionConfused2", null, null);	
	}
    
	// .............
	// #21: NPC1ShionRage

	void passageInit_21()
	{
		this.Passages["NPC1ShionRage"] = new TwinePassage("NPC1ShionRage", new string[]{  }, passageExecute_21);
	}

	IEnumerable<TwineOutput> passageExecute_21()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee (female): Hey you don't remember me? You used to work in the Q&A department before you transfered to the research division! Geeze...");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee (male): Well, don't give them a hard time, time are hard enough as it is with those...things wandering around.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee ( female) : Those shadow things....they are so creepy, pure black, moving shadows! t first you think it's a trick of they eye but.... I can't belive they are actually real.  thought they were rumors of people working too many overtime shifts.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionRage2", null, null);	
	}
    
	// .............
	// #22: ShionsConviction

	void passageInit_22()
	{
		this.Passages["ShionsConviction"] = new TwinePassage("ShionsConviction", new string[]{  }, passageExecute_22);
	}

	IEnumerable<TwineOutput> passageExecute_22()
	{
		yield return new TwineText(@"Shion : Ah... my head... why is it hurting?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"EquinoxNPCstalkingEnd", null, null);	
	}
    
	// .............
	// #23: Enteringtheresearchlab

	void passageInit_23()
	{
		this.Passages["Enteringtheresearchlab"] = new TwinePassage("Enteringtheresearchlab", new string[]{  }, passageExecute_23);
	}

	IEnumerable<TwineOutput> passageExecute_23()
	{
		yield return new TwineText(@"Shion: ... I remember being here... but I still can't remember what happened here... I need to look around more.");	
	}
    
	// .............
	// #24: AfterreadingthefinalnoteIfGoodShion

	void passageInit_24()
	{
		this.Passages["AfterreadingthefinalnoteIfGoodShion"] = new TwinePassage("AfterreadingthefinalnoteIfGoodShion", new string[]{  }, passageExecute_24);
	}

	IEnumerable<TwineOutput> passageExecute_24()
	{
		yield return new TwineText(@"(Shion reads the notes scattered around the room. These notes describe experiments with giving yin emotions a physical manifestation, types of shadow beasts. All of these notes are written in Shion's handwritting and are dated from the year before up until just last month. The most recent note reads "" It's too risky, I need to stop this research before it gets out of hand! I have to destroy all of this before-"" the rest is illegible...)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"AfterreadingthefinalnoteIfGoodShion2", null, null);	
	}
    
	// .............
	// #25: GoodShionpostBoss

	void passageInit_25()
	{
		this.Passages["GoodShionpostBoss"] = new TwinePassage("GoodShionpostBoss", new string[]{  }, passageExecute_25);
	}

	IEnumerable<TwineOutput> passageExecute_25()
	{
		yield return new TwineText(@"Shion: ....ha...Is it over?");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Kazkaza returns back to her original form in agony)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: HOW?! HOW COULD YOU DEFEAT ME?!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: How could you even allow yourself to continue this research! You are only brining harm! Look at what's happening to the people who work here! They are being attacked by the abominations we created!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue", @"Continue", @"GoodShionpostBoss2", null, null);	
	}
    
	// .............
	// #26: Kazkazaattempt

	void passageInit_26()
	{
		this.Passages["Kazkazaattempt"] = new TwinePassage("Kazkazaattempt", new string[]{  }, passageExecute_26);
	}

	IEnumerable<TwineOutput> passageExecute_26()
	{
		yield return new TwineText(@"(Shion attempts to speak to Kazkaza but she pays you no heed as she is barely concious now)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: I don't have time for this, I need to get out of here!");	
	}
    
	// .............
	// #27: Getoutofthepan

	void passageInit_27()
	{
		this.Passages["Getoutofthepan"] = new TwinePassage("Getoutofthepan", new string[]{  }, passageExecute_27);
	}

	IEnumerable<TwineOutput> passageExecute_27()
	{
		yield return new TwineText(@"Shion: I need to get out of here! Before it all burns down!");	
	}
    
	// .............
	// #28: AfterreadingfinalnoteIfBad

	void passageInit_28()
	{
		this.Passages["AfterreadingfinalnoteIfBad"] = new TwinePassage("AfterreadingfinalnoteIfBad", new string[]{  }, passageExecute_28);
	}

	IEnumerable<TwineOutput> passageExecute_28()
	{
		yield return new TwineText(@"(Shion reads the notes scattered around the room. These notes describe experiments with giving yin emotions a physical manifestation, types of shadow beasts. All of these notes are written in Shion's handwritting and are dated from the year before up until just last month. Notes are scribbled detailing how a to extract the energy from these creatures and put them inside someone else, transorming the recipient into a hybrid, some of these notes are in someone else's handwritting.Black stains make most of it illegible.)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"continue", @"continue", @"AfterreadingfinalnoteIfBad2", null, null);	
	}
    
	// .............
	// #29: BadShionpostboss

	void passageInit_29()
	{
		this.Passages["BadShionpostboss"] = new TwinePassage("BadShionpostboss", new string[]{  }, passageExecute_29);
	}

	IEnumerable<TwineOutput> passageExecute_29()
	{
		yield return new TwineText(@"Shion: It's finally over...");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Kazkaza returns to her human form and appears bloodied and distressed)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: HOW?! DO YOU KNOW HOW MUCH MONEY? RESEARCH WENT INTO THAT?!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Do I care? Not really, especially after what YOU did to me, incase you have forgotten.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: WHAT DO YOU KNOW?! I MADE YOU BETTER. YOU DIDN'T LISTEN TO ME! YOU WANTED TO HIDE YOUR RESEARCH FROM ME!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"continue", @"continue", @"BadShionpostboss2", null, null);	
	}
    
	// .............
	// #30: EpilogueGood

	void passageInit_30()
	{
		this.Passages["EpilogueGood"] = new TwinePassage("EpilogueGood", new string[]{  }, passageExecute_30);
	}

	IEnumerable<TwineOutput> passageExecute_30()
	{
		yield return new TwineText(@"After lighting their old lab on fire Kazkaza perishes in the fire, attempting to save information and research on the shadow beasts. A new CTO is placed into power a month after Kazkaza's death. The new CTO demolishes the research wing, replacing it with a wing devoted to research for the holophone.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Research on the shadow beasts stops as there is no one left, but there are still issues with the shadow beasts running rampant, remnants of Kazkaza's expiriments. Shion spends the rest of their life trying to remove of traces of these shadow beasts and help those affected by the attacks. ");
		yield return new TwineText(@"");
		yield return new TwineText(@"Eventually, Shion develops a serum to turn themselves back to being mostly human, but Shion still suffers from some of the quips of being mutated, in a good way, with the enhanced vision, Shion had obtainined staying with them.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"The End", @"The End", @"The End", null, null);	
	}
    
	// .............
	// #31: EpilogueBad

	void passageInit_31()
	{
		this.Passages["EpilogueBad"] = new TwinePassage("EpilogueBad", new string[]{  }, passageExecute_31);
	}

	IEnumerable<TwineOutput> passageExecute_31()
	{
		yield return new TwineText(@"Shion eliminates Kazkaza following the battle with the massive shadow beast, and furthers the research of the shadow beasts themselves.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion's research eventually makes them the new CTO of Equinox and instilling fear on the populous, mercilessly testing and enhancing the strength of the shadows using humans, and cultivating people to express strong enough emotions to give birth to strong shadow monsters.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion's actions eventually spurs rebellion in the commonfolk in the city and in the employee's of Equinox as well against Shion's inhumane treatement of test subjects.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion is in constant combat against those trying to destroy or steal thier research making them paranoid.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Eventually Shion goes insane with stress and frustration, and vanishes from Equinox. Rumors are heard of a massive shadow beast prowling the city and night attacking the unsuspecting...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"The End", @"The End", @"The End", null, null);	
	}
    
	// .............
	// #32: Mirror

	void passageInit_32()
	{
		this.Passages["Mirror"] = new TwinePassage("Mirror", new string[]{  }, passageExecute_32);
	}

	IEnumerable<TwineOutput> passageExecute_32()
	{
		yield return new TwineText(@"( Shion see's a mirror infront of them, the mirror twinkles eerily as Shion looks into it.)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: It feels like I'm being watched...", @"Shion: It feels like I'm being watched...", @"CreepyMirror", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion spends some time looking at their face in the mirror", @"Shion spends some time looking at their face in the mirror", @"SmirkingMirror", null, null);	
	}
    
	// .............
	// #33: Holophonebatteryrecoverysecond

	void passageInit_33()
	{
		this.Passages["Holophonebatteryrecoverysecond"] = new TwinePassage("Holophonebatteryrecoverysecond", new string[]{  }, passageExecute_33);
	}

	IEnumerable<TwineOutput> passageExecute_33()
	{
		disposition = 0;
		yield return new TwineText(@"Shion: Here it is! Well, time to get out of here!");	
	}
    
	// .............
	// #34: Holophonerecoverysecond

	void passageInit_34()
	{
		this.Passages["Holophonerecoverysecond"] = new TwinePassage("Holophonerecoverysecond", new string[]{  }, passageExecute_34);
	}

	IEnumerable<TwineOutput> passageExecute_34()
	{
		disposition = 0;
		yield return new TwineText(@"Shion: My holophone! I found the battery earlier, I just have to put it together and it should be good to go!");	
	}
    
	// .............
	// #35: Holophonebatteryrecoveryfirst

	void passageInit_35()
	{
		this.Passages["Holophonebatteryrecoveryfirst"] = new TwinePassage("Holophonebatteryrecoveryfirst", new string[]{  }, passageExecute_35);
	}

	IEnumerable<TwineOutput> passageExecute_35()
	{
		disposition = 0;
		yield return new TwineText(@"Shion: This looks like a holophone battery. I'll just take this with me for now.");	
	}
    
	// .............
	// #36: Desk

	void passageInit_36()
	{
		this.Passages["Desk"] = new TwinePassage("Desk", new string[]{  }, passageExecute_36);
	}

	IEnumerable<TwineOutput> passageExecute_36()
	{
		disposition = 0;
		yield return new TwineText(@"");
		yield return new TwineText(@"( Shion sees a messy desk with numerous items and papers spread about. A glimmering object catches Shion's eye and on inspection it appears to be a small jeweled cat ornament that appears to be a paper weight)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: It's pretty, but it's not mine. I'll just leave it here", @"Shion: It's pretty, but it's not mine. I'll just leave it here", @"JeweledCat", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: It's pretty, looks like it's a waste amongst this filth. I'll take it with me.", @"Shion: It's pretty, looks like it's a waste amongst this filth. I'll take it with me.", @"PrettyJeweledCat", null, null);	
	}
    
	// .............
	// #37: CreepyMirror

	void passageInit_37()
	{
		this.Passages["CreepyMirror"] = new TwinePassage("CreepyMirror", new string[]{  }, passageExecute_37);
	}

	IEnumerable<TwineOutput> passageExecute_37()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: I don't think I should stare at this anymore...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level1End", null, null);	
	}
    
	// .............
	// #38: SmirkingMirror

	void passageInit_38()
	{
		this.Passages["SmirkingMirror"] = new TwinePassage("SmirkingMirror", new string[]{  }, passageExecute_38);
	}

	IEnumerable<TwineOutput> passageExecute_38()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"( Shion's reflection in the mirror smirks at Shion)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Well, maybe I haven't recovered enough yet...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level1End", null, null);	
	}
    
	// .............
	// #39: JeweledCat

	void passageInit_39()
	{
		this.Passages["JeweledCat"] = new TwinePassage("JeweledCat", new string[]{  }, passageExecute_39);
	}

	IEnumerable<TwineOutput> passageExecute_39()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: This place really needs to be cleaned up...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level1End", null, null);	
	}
    
	// .............
	// #40: PrettyJeweledCat

	void passageInit_40()
	{
		this.Passages["PrettyJeweledCat"] = new TwinePassage("PrettyJeweledCat", new string[]{  }, passageExecute_40);
	}

	IEnumerable<TwineOutput> passageExecute_40()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: It's for the best really..");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level1End", null, null);	
	}
    
	// .............
	// #41: NegativeShionKazkaza

	void passageInit_41()
	{
		this.Passages["NegativeShionKazkaza"] = new TwinePassage("NegativeShionKazkaza", new string[]{  }, passageExecute_41);
	}

	IEnumerable<TwineOutput> passageExecute_41()
	{
		disposition = 0;
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza : Well, maybe you really did end up drinking too much at the company party, hmm? Well, no matter, I have quite a bit of work to do, but I'll work on getting your phones information restored, It'll be kinda a pain though, and it might take a while for me to bring all the data back to you, I tell ya, cloud storage is a monster to deal with! ");yield return new TwineLink(@"Well it'll go faster if you help me out with a problem", @"Well it'll go faster if you help me out with a problem", @"KazkazaRequest", null, null);	
	}
    
	// .............
	// #42: PositiveShionKazkaza

	void passageInit_42()
	{
		this.Passages["PositiveShionKazkaza"] = new TwinePassage("PositiveShionKazkaza", new string[]{  }, passageExecute_42);
	}

	IEnumerable<TwineOutput> passageExecute_42()
	{
		disposition = 0;
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: That's not my issue. Everyone's gotta take out their issues on IT.  I'll do it, it won't be easy since I have to pull it from the cloud and I have other work to do y'anno, it's not like you're the only one with holophone issues right now. ");yield return new TwineLink(@"Well it'll go faster if you help me out with a problem", @"Well it'll go faster if you help me out with a problem", @"KazkazaRequest", null, null);	
	}
    
	// .............
	// #43: Thearmgrows

	void passageInit_43()
	{
		this.Passages["Thearmgrows"] = new TwinePassage("Thearmgrows", new string[]{  }, passageExecute_43);
	}

	IEnumerable<TwineOutput> passageExecute_43()
	{
		yield return new TwineText(@"(Shion suddenly collapses in pain upon entering the warehouse, the pain is originating from Shion's arm)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: AHHH! What?! ");
		yield return new TwineText(@"");
		yield return new TwineText(@"(screen blacks out, when it comes back Shion's arm has rubbery like consistancy, letting it expand and stretch to unnatural lengths.)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: What...what is this? What happened to me?!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(Return)", @"(Return)", @"Level2End", null, null);	
	}
    
	// .............
	// #44: Obtainparts

	void passageInit_44()
	{
		this.Passages["Obtainparts"] = new TwinePassage("Obtainparts", new string[]{  }, passageExecute_44);
	}

	IEnumerable<TwineOutput> passageExecute_44()
	{
		yield return new TwineText(@"Shion: Just a few more to go...");	
	}
    
	// .............
	// #45: Lastpart

	void passageInit_45()
	{
		this.Passages["Lastpart"] = new TwinePassage("Lastpart", new string[]{  }, passageExecute_45);
	}

	IEnumerable<TwineOutput> passageExecute_45()
	{
		yield return new TwineText(@"Shion: Finally! The last part! Time to get out of here!");	
	}
    
	// .............
	// #46: Sealingthewarehouse

	void passageInit_46()
	{
		this.Passages["Sealingthewarehouse"] = new TwinePassage("Sealingthewarehouse", new string[]{  }, passageExecute_46);
	}

	IEnumerable<TwineOutput> passageExecute_46()
	{
		yield return new TwineText(@"Shion: Yep, this feels like the way it was on the picture! Just a few more seals to go!");	
	}
    
	// .............
	// #47: Unsleaingthewarehouse

	void passageInit_47()
	{
		this.Passages["Unsleaingthewarehouse"] = new TwinePassage("Unsleaingthewarehouse", new string[]{  }, passageExecute_47);
	}

	IEnumerable<TwineOutput> passageExecute_47()
	{
		yield return new TwineText(@"Shion: I don't think this is the right order...");	
	}
    
	// .............
	// #48: Finishedtheseal

	void passageInit_48()
	{
		this.Passages["Finishedtheseal"] = new TwinePassage("Finishedtheseal", new string[]{  }, passageExecute_48);
	}

	IEnumerable<TwineOutput> passageExecute_48()
	{
		yield return new TwineText(@"Shion: Looks like that's the last of it!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(A booming noise comes from above, for the sounds of it, it's from a old Com system)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Big Boss: AY! YOU DID IT KIDDO! LETS GET YOU OUTTA HERE!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(The exit unlocks)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"Level2End", null, null);	
	}
    
	// .............
	// #49: CasualShion

	void passageInit_49()
	{
		this.Passages["CasualShion"] = new TwinePassage("CasualShion", new string[]{  }, passageExecute_49);
	}

	IEnumerable<TwineOutput> passageExecute_49()
	{
		disposition += 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Geeze, don't be so polite, we work for the same company after all....but so does almost everyone who lives here so.....well no matter, thanks for the parts! Give me your holophone real quick. I have something that might interest you that I happened to find!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Kazkaza takes the phone and plugs it into one of the many cables lying around, after punching a few things into her keyboard she unplugs it and hands it back to Shion)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Giving info", @"Giving info", @"Givinginfo", null, null);	
	}
    
	// .............
	// #50: AnnoyedShion

	void passageInit_50()
	{
		this.Passages["AnnoyedShion"] = new TwinePassage("AnnoyedShion", new string[]{  }, passageExecute_50);
	}

	IEnumerable<TwineOutput> passageExecute_50()
	{
		disposition -= 15;
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: You researchers, all the same, no manners. Well whatever, I found something that probably interests you, give me your holophone for a bit.");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Kazkaza takes the phone and plugs it into one of the many cables lying around, after punching a few things into her keyboard she unplugs it and hands it back to Shion)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: ...researcher?...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Giving info", @"Giving info", @"Givinginfo", null, null);	
	}
    
	// .............
	// #51: ShionConfused2

	void passageInit_51()
	{
		this.Passages["ShionConfused2"] = new TwinePassage("ShionConfused2", new string[]{  }, passageExecute_51);
	}

	IEnumerable<TwineOutput> passageExecute_51()
	{
		yield return new TwineText(@"Equinox Employee ( female) : Yeah, Shion here transfered to the research division a while back, you know, the wing that got shut down recently. they probably know something about it, since that's where everyone is saying these shadows are comming from.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: I'm sorry, I actually got into an accident recently, I dont'...I don't remember what I was working on much.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionConfused3", null, null);	
	}
    
	// .............
	// #52: ShionRage2

	void passageInit_52()
	{
		this.Passages["ShionRage2"] = new TwinePassage("ShionRage2", new string[]{  }, passageExecute_52);
	}

	IEnumerable<TwineOutput> passageExecute_52()
	{
		yield return new TwineText(@"Equinox Employee (male): Well, they are most certainely real. I can't belive managment isn't doing anything about them.They told us they are containing them and doing something about it. But people are still being attacked by them!");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee ( female) : We should get out of this company...I think what some of the staff are saying is true. Those...things, they came from the closed wing.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee ( male) : I think that's enough talk about this. Talking about wild conspiracy theories won't get us anywhere anyways...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionRage3", null, null);	
	}
    
	// .............
	// #53: ShionvsKazkazaGood

	void passageInit_53()
	{
		this.Passages["ShionvsKazkazaGood"] = new TwinePassage("ShionvsKazkazaGood", new string[]{  }, passageExecute_53);
	}

	IEnumerable<TwineOutput> passageExecute_53()
	{
		yield return new TwineText(@"Kazkaza: That's right! Wow, you were much faster than I thought! But then again I should have expected as much from the person who discovered the shadows beasts.The person who gave them physical form, in a lot of ways, you are their parent. After all, these shadows that are roaming around are mostly yours.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: ...Mine?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaGood2", null, null);	
	}
    
	// .............
	// #54: ShionvsKazkazaGood2

	void passageInit_54()
	{
		this.Passages["ShionvsKazkazaGood2"] = new TwinePassage("ShionvsKazkazaGood2", new string[]{  }, passageExecute_54);
	}

	IEnumerable<TwineOutput> passageExecute_54()
	{
		yield return new TwineText(@"Kazkaza: Aparently you still don't remember enough, interesting. Well it's easy, the strongest of emotions, regret, despair, guilt, shadows are made of these, fueled by this. A lot of the shadows here are from yourself, but they are not all yours...");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Emotions...I remember, I was doing research on shadows, on utilizing negative emotional energy in a way to benifit everyone, a way to remove the negative emotions from people while making use of those emotions.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaGood3", null, null);	
	}
    
	// .............
	// #55: ShionvsKazkazaGood3

	void passageInit_55()
	{
		this.Passages["ShionvsKazkazaGood3"] = new TwinePassage("ShionvsKazkazaGood3", new string[]{  }, passageExecute_55);
	}

	IEnumerable<TwineOutput> passageExecute_55()
	{
		yield return new TwineText(@"Kazkaza: Oh good, I don't have to explain everything it seems. Well then let's get down to business. Work with me again. I can't manage everything being a CTO and trying to cultivate these shadows gives me close to no free time these days.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: What are you planning to do with the shadows? What are you doing with them right now?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaGood4", null, null);	
	}
    
	// .............
	// #56: ShionvsKazkazaBad

	void passageInit_56()
	{
		this.Passages["ShionvsKazkazaBad"] = new TwinePassage("ShionvsKazkazaBad", new string[]{  }, passageExecute_56);
	}

	IEnumerable<TwineOutput> passageExecute_56()
	{
		yield return new TwineText(@"Kazkaza: That's right! Wow, you were much faster than I thought! But then again I should have expected as much from the person who discovered the shadows beasts.The person who gave them physical form, in a lot of ways, you are their parent. After all, these shadows that are roaming around are mostly yours.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Mine? Those came from me?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaBad2", null, null);	
	}
    
	// .............
	// #57: ShionvsKazkazaBad2

	void passageInit_57()
	{
		this.Passages["ShionvsKazkazaBad2"] = new TwinePassage("ShionvsKazkazaBad2", new string[]{  }, passageExecute_57);
	}

	IEnumerable<TwineOutput> passageExecute_57()
	{
		yield return new TwineText(@"Kazkaza: Aparently you still don't remember enough, interesting. Well it's easy, the strongest of emotions, regret, despair, guilt, shadows are made of these, fueled by this. A lot of the shadows here are from yourself, but they are not all yours...");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Emotions, huh? I recall it a bit now that you mention it. I was doing research on shadows, on utilizing negative emotional energy to be benificial.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaBad3", null, null);	
	}
    
	// .............
	// #58: ShionConfused3

	void passageInit_58()
	{
		this.Passages["ShionConfused3"] = new TwinePassage("ShionConfused3", new string[]{  }, passageExecute_58);
	}

	IEnumerable<TwineOutput> passageExecute_58()
	{
		yield return new TwineText(@"Equinox Employee ( female) : Sorry to hear that. Well.. I guess we'll never know. But between all of you and me, I think those shadow beasts came from that wing. Why else would we be the only place in the entire city with the most reports of them? Not to mention the wing got shut down right after they started poppingup all-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Equinox Employee ( male) : I think that's enough talk about this.Talking about some wild conspiracy theories won't get us anywhere anyways...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionConfused4", null, null);	
	}
    
	// .............
	// #59: ShionConfused4

	void passageInit_59()
	{
		this.Passages["ShionConfused4"] = new TwinePassage("ShionConfused4", new string[]{  }, passageExecute_59);
	}

	IEnumerable<TwineOutput> passageExecute_59()
	{
		yield return new TwineText(@"( The two NPC's go back to their chattering seemingly forgetting Shion's prescence)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: Sounds like there really must be more to the research wing, but I need more information, if the shadow beasts are really comming from in there, then I need to be prepaired. I need more information ", @"Shion: Sounds like there really must be more to the research wing, but I need more information, if the shadow beasts are really comming from in there, then I need to be prepaired. I need more information ", @"ShionsConviction", null, null);	
	}
    
	// .............
	// #60: ShionRage3

	void passageInit_60()
	{
		this.Passages["ShionRage3"] = new TwinePassage("ShionRage3", new string[]{  }, passageExecute_60);
	}

	IEnumerable<TwineOutput> passageExecute_60()
	{
		yield return new TwineText(@"( The two NPC's go back to their chattering seemingly forgetting Shion's prescence)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: I need to get into the research wing, there must be a way in, but I can't go in there unprepaired, there must be some place that has more information... the place I woke up. there must be something there, but how do I go there? The way sealed itself when I left that place? ", @"Shion: I need to get into the research wing, there must be a way in, but I can't go in there unprepaired, there must be some place that has more information... the place I woke up. there must be something there, but how do I go there? The way sealed itself when I left that place? ", @"ShionsConviction", null, null);	
	}
    
	// .............
	// #61: AfterreadingthefinalnoteIfGoodShion2

	void passageInit_61()
	{
		this.Passages["AfterreadingthefinalnoteIfGoodShion2"] = new TwinePassage("AfterreadingthefinalnoteIfGoodShion2", new string[]{  }, passageExecute_61);
	}

	IEnumerable<TwineOutput> passageExecute_61()
	{
		yield return new TwineText(@"Shion: I...I created these monsters. I did this, my research created these...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaGood", null, null);	
	}
    
	// .............
	// #62: AfterreadingfinalnoteIfBad2

	void passageInit_62()
	{
		this.Passages["AfterreadingfinalnoteIfBad2"] = new TwinePassage("AfterreadingfinalnoteIfBad2", new string[]{  }, passageExecute_62);
	}

	IEnumerable<TwineOutput> passageExecute_62()
	{
		yield return new TwineText(@"Shion: Hm. I knew I was connected to this, but I didn't think I would be in the midst of it... yin emotions... taking the negative emotions of others and turning it into a physical manifiestation... But how are there so many shadow monsters everywhere?");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaBad", null, null);	
	}
    
	// .............
	// #63: ShionvsKazkazaBad3

	void passageInit_63()
	{
		this.Passages["ShionvsKazkazaBad3"] = new TwinePassage("ShionvsKazkazaBad3", new string[]{  }, passageExecute_63);
	}

	IEnumerable<TwineOutput> passageExecute_63()
	{
		yield return new TwineText(@"Kazkaza: Oh good, I don't have to explain everything it seems. Well then let's get down to business. Work with me again. I can't manage everything being a CTO and trying to cultivate these shadows gives me close to no free time these days.");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Why would I trust someone like you, clearly you did something to me to affect my memory, and you are most likely the reason why I'm suffering from my current...ailment.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaBad4", null, null);	
	}
    
	// .............
	// #64: ShionvsKazkazaBad4

	void passageInit_64()
	{
		this.Passages["ShionvsKazkazaBad4"] = new TwinePassage("ShionvsKazkazaBad4", new string[]{  }, passageExecute_64);
	}

	IEnumerable<TwineOutput> passageExecute_64()
	{
		yield return new TwineText(@"Kazkaza: You had it comming, you wouldn't listen to me! And in the end isn't it fine? Your research has become much more effective now that I've taken it over, and you are much stronger now!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Fine? You think it's fine just because I've aquired some new abilities? I liked how I was before much more! How dare you try to steal MY research and use it against me!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaBad5", null, null);	
	}
    
	// .............
	// #65: ShionvsKazkazaGood4

	void passageInit_65()
	{
		this.Passages["ShionvsKazkazaGood4"] = new TwinePassage("ShionvsKazkazaGood4", new string[]{  }, passageExecute_65);
	}

	IEnumerable<TwineOutput> passageExecute_65()
	{
		yield return new TwineText(@"Kazkaza: These shadows can do many things, I don't think we've discovered the full extent of their abilities yet, either. But imagine, to have the control on the emotions of others, to pull the emotions out of others and utilize them, we can remove the negative emotions from people, and make them work optimally, imagine! No pain and agony! And we can use the negative energy however we want once we learn how to use it!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: We can't play with people emotions like that! Emotions make a person, the expression of our emotions is how we convey ourselves to each other!To take them away turns us into monsters! Yin cannot exist without yang!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaGood5", null, null);	
	}
    
	// .............
	// #66: ShionvsKazkazaGood5

	void passageInit_66()
	{
		this.Passages["ShionvsKazkazaGood5"] = new TwinePassage("ShionvsKazkazaGood5", new string[]{  }, passageExecute_66);
	}

	IEnumerable<TwineOutput> passageExecute_66()
	{
		yield return new TwineText(@"Kazkaza: Doesn't matter to me, the way I see it, we are all monsters, what I do removes the demons from ourselves and pulls them to the outside. But...you know are you not worse than myself? You are the one who discovered this method after all!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion But... I?!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: Silence dear. Like I told you before I don't have that much free time, and I can see that you won't work for me, so It's time for us to end this relationship. Pity, I had hoped that when I enjected the essense of the shadows into you that you would have seen things differently. Look how strong you are now. Oh well. Pity.");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(continue)", @"(continue)", @"ShionvsKazkazaGood6", null, null);	
	}
    
	// .............
	// #67: ShionvsKazkazaGood6

	void passageInit_67()
	{
		this.Passages["ShionvsKazkazaGood6"] = new TwinePassage("ShionvsKazkazaGood6", new string[]{  }, passageExecute_67);
	}

	IEnumerable<TwineOutput> passageExecute_67()
	{
		yield return new TwineText(@"(Kazkaza pulls out a needle and injects herself with a dark liquid. As it disapears into her she lets out a murderous shriek as she turns onto a large spider-like shadow beast. She looks like she is going to attack Shion!)");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: NOW!! LETS SEE YOU RUN!!! HAHAHAHA");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"FinaleIntroEnd", null, null);	
	}
    
	// .............
	// #68: The End

	void passageInit_68()
	{
		this.Passages["The End"] = new TwinePassage("The End", new string[]{  }, passageExecute_68);
	}

	IEnumerable<TwineOutput> passageExecute_68()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #69: GoodShionpostBoss2

	void passageInit_69()
	{
		this.Passages["GoodShionpostBoss2"] = new TwinePassage("GoodShionpostBoss2", new string[]{  }, passageExecute_69);
	}

	IEnumerable<TwineOutput> passageExecute_69()
	{
		yield return new TwineText(@"Kazkaza: WHAT DO YOU KNOW?! THOSE PEOPLE WERE GOING TO DIE AWFUL PITIFUL DEATHS ANYWAYS!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: We can't judge who's life is worth living and who's is not. It was never our place, and it was never the intent of the research I did, you twisted it to your own ideals. I belived harnessing the power of human emotions and desires would be benificial somwhow, now I see how wrong I was...");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Continue", @"Continue", @"GoodShionpostBoss3", null, null);	
	}
    
	// .............
	// #70: GoodShionpostBoss3

	void passageInit_70()
	{
		this.Passages["GoodShionpostBoss3"] = new TwinePassage("GoodShionpostBoss3", new string[]{  }, passageExecute_70);
	}

	IEnumerable<TwineOutput> passageExecute_70()
	{
		yield return new TwineText(@"Kazkaza: You can't see the benifits? We rip the emotions from people, give them forms, and if we can control them, imagine how much we can be capable of!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Not anymore. I won't let this continue!");
		yield return new TwineText(@"");
		yield return new TwineText(@"( Shion takes a nearby flamable substance, (something used in the boss fight prefered) and lights the desk on fire which quickly consumes the room)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: ARE YOU MAD! HOW CAN YOU DO THIS? THIS RESEARCH IS THE FUTURE OF EQUINOX, MY FURTURE!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"ShionpostBossEnd", null, null);	
	}
    
	// .............
	// #71: BadShionpostboss2

	void passageInit_71()
	{
		this.Passages["BadShionpostboss2"] = new TwinePassage("BadShionpostboss2", new string[]{  }, passageExecute_71);
	}

	IEnumerable<TwineOutput> passageExecute_71()
	{
		yield return new TwineText(@"Shion: Yeah! Because you are clearly insane, that's why! Again, I didn't ask you to make me ""better"" and YOU stole MY research because you couldn't get anything done otherwise! You didn't have the ability or skills to discover what I did!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: You say that but look at you! In the end you are a monster, you have nothing! I'm the CTO of Equinox not you! I have-");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Not anymore! I won't let this continue, I'm taking back what's mine!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"continue", @"continue", @"BadShionpostboss3", null, null);	
	}
    
	// .............
	// #72: BadShionpostboss3

	void passageInit_72()
	{
		this.Passages["BadShionpostboss3"] = new TwinePassage("BadShionpostboss3", new string[]{  }, passageExecute_72);
	}

	IEnumerable<TwineOutput> passageExecute_72()
	{
		yield return new TwineText(@"( Shion stabs Kazkaza with their arm)");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: ARE YOU MAD! HOW CAN YOU DO THIS?! I'M SUPPOSED TO LEAD EQUINOX INTO THE NEW AGE!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Not anymore! I'm taking back my place!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: AAAAAAAAAH!");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Kazkaza's form vanishes into a couple of shadow monsters, produced by her anguish and rage)");
		yield return new TwineText(@"");
		yield return new TwineLink(@"continue", @"continue", @"BadShionpostboss4", null, null);	
	}
    
	// .............
	// #73: BadShionpostboss4

	void passageInit_73()
	{
		this.Passages["BadShionpostboss4"] = new TwinePassage("BadShionpostboss4", new string[]{  }, passageExecute_73);
	}

	IEnumerable<TwineOutput> passageExecute_73()
	{
		yield return new TwineText(@"Shion: I better get out of here, that's one too many fights for one day!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"ShionpostBossEnd", null, null);	
	}
    
	// .............
	// #74: ShionvsKazkazaBad5

	void passageInit_74()
	{
		this.Passages["ShionvsKazkazaBad5"] = new TwinePassage("ShionvsKazkazaBad5", new string[]{  }, passageExecute_74);
	}

	IEnumerable<TwineOutput> passageExecute_74()
	{
		yield return new TwineText(@"Kazkaza: A pity...It seems you cannot be reasoned with. So I guess I'll just have to take you out myself... Let yourself be destroyed by me and I'll make it easy for you, I promise...");
		yield return new TwineText(@"");
		yield return new TwineText(@"(Kazkaza pulls out a needle and injects herself with a dark liquid. As it disapears into her she lets out a murderous shriek as she turns onto a large spider-like shadow beast. She glares at Shion and starts her attack!)");
		yield return new TwineText(@"");
		yield return new TwineText(@"");
		yield return new TwineText(@"Kazkaza: NOW!! LETS SEE YOU RUN!!! HAHAHAHA");
		yield return new TwineText(@"");
		yield return new TwineLink(@"(End Conversation)", @"(End Conversation)", @"FinaleIntroEnd", null, null);	
	}
    
	// .............
	// #75: Talktobigboss2

	void passageInit_75()
	{
		this.Passages["Talktobigboss2"] = new TwinePassage("Talktobigboss2", new string[]{  }, passageExecute_75);
	}

	IEnumerable<TwineOutput> passageExecute_75()
	{
		yield return new TwineText(@"Big Boss: Kazkaza, by Urgot ‘imself I knew this would happen eventually. Kazkaza's been picking me noggin for them parts for a 4 days now now. The woman's pretty persistent, at least she sent someone in person this time!");
		yield return new TwineText(@"");
		yield return new TwineText(@"Shion: Is there a problem with the parts she ordered?");
		yield return new TwineText(@"");
		yield return new TwineLink(@"continue", @"continue", @"Talktobigboss3", null, null);	
	}
    
	// .............
	// #76: Talktobigboss3

	void passageInit_76()
	{
		this.Passages["Talktobigboss3"] = new TwinePassage("Talktobigboss3", new string[]{  }, passageExecute_76);
	}

	IEnumerable<TwineOutput> passageExecute_76()
	{
		yield return new TwineText(@"Big Boss (sighs): Not really an issue with the parts ya see. The issue is the warehouse has been a complete wreck since those whacko shadow things showed up 5 days ago. None of us can do a darn tootin' thing because of those pests!");
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: Is there some way I can get in there and get the parts myself? I need them quite urgently.", @"Shion: Is there some way I can get in there and get the parts myself? I need them quite urgently.", @"NiceBoss", null, null);
		yield return new TwineText(@"");
		yield return new TwineLink(@"Shion: Shadows? I think I can deal with those, let me in. I'll go grab the parts myself.", @"Shion: Shadows? I think I can deal with those, let me in. I'll go grab the parts myself.", @"SmirkingBoss", null, null);	
	}
    
	// .............
	// #77: MeetingmakeupwipesEnd

	void passageInit_77()
	{
		this.Passages["MeetingmakeupwipesEnd"] = new TwinePassage("MeetingmakeupwipesEnd", new string[]{  }, passageExecute_77);
	}

	IEnumerable<TwineOutput> passageExecute_77()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #78: ShionpostBossEnd

	void passageInit_78()
	{
		this.Passages["ShionpostBossEnd"] = new TwinePassage("ShionpostBossEnd", new string[]{  }, passageExecute_78);
	}

	IEnumerable<TwineOutput> passageExecute_78()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #79: KazkazarequestEnd

	void passageInit_79()
	{
		this.Passages["KazkazarequestEnd"] = new TwinePassage("KazkazarequestEnd", new string[]{  }, passageExecute_79);
	}

	IEnumerable<TwineOutput> passageExecute_79()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #80: FinaleIntroEnd

	void passageInit_80()
	{
		this.Passages["FinaleIntroEnd"] = new TwinePassage("FinaleIntroEnd", new string[]{  }, passageExecute_80);
	}

	IEnumerable<TwineOutput> passageExecute_80()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #81: EquinoxNPCstalkingEnd

	void passageInit_81()
	{
		this.Passages["EquinoxNPCstalkingEnd"] = new TwinePassage("EquinoxNPCstalkingEnd", new string[]{  }, passageExecute_81);
	}

	IEnumerable<TwineOutput> passageExecute_81()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #82: Level1End

	void passageInit_82()
	{
		this.Passages["Level1End"] = new TwinePassage("Level1End", new string[]{  }, passageExecute_82);
	}

	IEnumerable<TwineOutput> passageExecute_82()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #83: Level2End

	void passageInit_83()
	{
		this.Passages["Level2End"] = new TwinePassage("Level2End", new string[]{  }, passageExecute_83);
	}

	IEnumerable<TwineOutput> passageExecute_83()
	{
		yield return new TwineText(@"");	
	}
    
	// .............
	// #84: Obtainingtheparts

	void passageInit_84()
	{
		this.Passages["Obtainingtheparts"] = new TwinePassage("Obtainingtheparts", new string[]{  }, passageExecute_84);
	}

	IEnumerable<TwineOutput> passageExecute_84()
	{
		yield return new TwineText(@"Shion: How am I supposed to reach those parts from here?... Maybe with my new arm I can...I should try.");	
	}

}